name: linuxserver-webtop
services:
  app:
    image: linuxserver/webtop:arch-kde-version-2025-07-12@sha256:c024d2b43174539f6a376c47d168bc7b05ec9109f921e6d49f0b01e22fefc7be
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/webtop/config
        target: /config
