name: big-bear-flame
services:
  app:
    image: pawelmalak/flame:multiarch2.3.1
    environment:
      PASSWORD: casaos
    restart: unless-stopped
    ports:
      - target: 5005
        published: '5005'
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /app/data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
