name: big-bear-unifi-network-application-mongo-4
services:
  unifi-db:
    image: mongo:4.4.28
    container_name: big-bear-unifi-db
    volumes:
      - /DATA/AppData/$AppID/db/data:/data/db
      - >-
        /DATA/AppData/big-bear-unifi-network-application/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - '27017:27017'
    networks:
      - unifi-nework-application-network
    restart: unless-stopped
  app:
    image: linuxserver/unifi-network-application:9.3.45
    container_name: big-bear-unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_HOST=big-bear-unifi-db
      - MONGO_USER=unifi
      - MONGO_PASS=unifi_password
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024
      - MEM_STARTUP=1024
      - MONGO_TLS=
      - MONGO_AUTHSOURCE=
    volumes:
      - /DATA/AppData/$AppID/config:/config
    ports:
      - '8443:8443'
      - 3478:3478/udp
      - 10001:10001/udp
      - '8080:8080'
      - 1900:1900/udp
      - '8843:8843'
      - '8880:8880'
      - '6789:6789'
      - 5514:5514/udp
    restart: unless-stopped
    networks:
      - unifi-nework-application-network
    depends_on:
      - unifi-db
networks:
  unifi-nework-application-network:
    driver: bridge
