name: yuvomi

services:
  yuvomi:
    image: ghcr.io/ulsklyc/yuvomi:2.73.0@sha256:86b874876612aa880bc5ce18563b2cd502e2230263aa3cc3a679d9d1245de938
    container_name: yuvomi
    restart: unless-stopped
    ports:
      - "20004:3000"
    volumes:
      - yuvomi_data:/data
      - yuvomi_backups:/backups
      - yuvomi_modules:/app/modules
      - yuvomi_documents:/documents
    environment:
      NODE_ENV: production
      PORT: "3000"
      DB_PATH: /data/yuvomi.db
      BACKUP_DIR: /backups
      MODULES_DIR: /app/modules
      SESSION_SECRET: PtfaK2EYBfghFZZH_zV8spJAnLX-t4cXt-rMFwRn9mVKpdaU0PTD2gpEqheIx7Jk
      DB_ENCRYPTION_KEY: 12C_F5m7nZC69qeJlJL0BqgCNd8lH3m1zqAeERMcG3g
      SESSION_SECURE: "false"
      TRUST_PROXY: loopback
      DOCUMENT_STORAGE_LOCAL_ENABLED: "false"
      DOCUMENT_STORAGE_LOCAL_PATH: /documents
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', r => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  yuvomi_data:
    name: yuvomi_data
    driver: local
  yuvomi_backups:
    name: yuvomi_backups
    driver: local
  yuvomi_modules:
    name: yuvomi_modules
    driver: local
  yuvomi_documents:
    name: yuvomi_documents
    driver: local
