name: big-bear-bookstack
services:
  big-bear-bookstack:
    container_name: big-bear-bookstack
    image: linuxserver/bookstack:25.07.20250804
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/config:/config
    environment:
      - APP_KEY=base64:3w/hRS2HYVFH5tJqD9AFlyurTh8mBByMKeMRyH9kEEQ=
      - APP_URL=http://[change to your IP]:8080
      - DB_HOST=big-bear-bookstack-db
      - DB_USERNAME=bigbear
      - DB_PASSWORD=a3e8949f-484c-4877-afdb-391f892f9bb6
      - DB_DATABASE=bookstackapp
    ports:
      - '8080:80'
    depends_on:
      - big-bear-bookstack-db
    networks:
      - big_bear_bookstack_network
  big-bear-bookstack-db:
    image: linuxserver/mariadb:10.11.6
    container_name: big-bear-bookstack-db
    environment:
      - MYSQL_ROOT_PASSWORD=793e92b7-58d2-47b9-aae5-b8c7d58bd699
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bigbear
      - MYSQL_PASSWORD=a3e8949f-484c-4877-afdb-391f892f9bb6
    volumes:
      - /DATA/AppData/$AppID/mysql:/config
    restart: unless-stopped
    networks:
      - big_bear_bookstack_network
networks:
  big_bear_bookstack_network:
    driver: bridge
