name: big-bear-homepage
services:
  app:
    image: ghcr.io/gethomepage/homepage:v1.4.6
    container_name: homepage
    ports:
      - '3000:3000'
    volumes:
      - /DATA/AppData/$AppID/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
