name: big-bear-dockge
services:
  app:
    container_name: big-bear-dockge
    image: louislam/dockge:1.5.0
    environment:
      DOCKGE_STACKS_DIR: /DATA/AppData/big-bear-dockge/stacks
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /DATA/AppData/$AppID/data:/app/data
      - /DATA/AppData/$AppID/stacks:/DATA/AppData/big-bear-dockge/stacks
    ports:
      - '5001:5001'
