name: linuxserver-kdenlive
services:
  app:
    image: linuxserver/kdenlive:26.08.1@sha256:c7d11daa16e22f9efa8fc59222bdbb13e35548b8ab774028dfcd3309c98bc85c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/kdenlive/config
        target: /config
