name: big-bear-otel-lgtm
services:
  big-bear-otel-lgtm:
    container_name: big-bear-otel-lgtm
    image: grafana/otel-lgtm:0.11.9
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
        bind:
          create_host_path: true
    ports:
      - mode: ingress
        target: 3000
        published: '3000'
        protocol: tcp
      - mode: ingress
        target: 4317
        published: '4317'
        protocol: tcp
      - mode: ingress
        target: 4318
        published: '4318'
        protocol: tcp
    networks:
      - big-bear-otel-lgtm
networks:
  big-bear-otel-lgtm:
    driver: bridge
