name: big-bear-viseron
services:
  big-bear-viseron:
    container_name: big-bear-viseron
    image: roflcoopter/viseron:3.2.3
    restart: unless-stopped
    shm_size: 1024mb
    volumes:
      - /DATA/AppData/$AppID/segments:/segments
      - /DATA/AppData/$AppID/snapshots:/snapshots
      - /DATA/AppData/$AppID/thumbnails:/thumbnails
      - /DATA/AppData/$AppID/event_clips:/event_clips
      - /DATA/AppData/$AppID/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8888:8888'
    environment:
      - PUID=1000
      - PGID=1000
