name: big-bear-onlyoffice
services:
  app:
    image: onlyoffice/documentserver:9.0.4
    container_name: documentserver
    ports:
      - '7400:80'
    volumes:
      - /DATA/AppData/$AppID/onlyoffice/logs:/var/log/onlyoffice
      - /DATA/AppData/$AppID/onlyoffice/data:/var/www/onlyoffice/Data
      - /DATA/AppData/$AppID/onlyoffice/lib:/var/lib/onlyoffice
      - /DATA/AppData/$AppID/onlyoffice/rabbitmq:/var/lib/rabbitmq
      - /DATA/AppData/$AppID/onlyoffice/redis:/var/lib/redis
      - /DATA/AppData/$AppID/onlyoffice/db:/var/lib/postgresql
