name: linuxserver-ungoogled-chromium
services:
  app:
    image: linuxserver/ungoogled-chromium:155.0.8059@sha256:d0730ec58f4befff20dc4cd6651c88fa656e1689fb1a084452be4841ee794cad
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CHROME_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ungoogled-chromium/config
        target: /config
