name: linuxserver-msedge
services:
  app:
    image: linuxserver/msedge:155.0.4283@sha256:819faf7b2332f7965a58d9fc1add44ee352bfcf9f018c893323d16cb891a26e2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      EDGE_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/msedge/config
        target: /config
