name: linuxserver-msedge
services:
  app:
    image: linuxserver/msedge:154.0.4258@sha256:f0ce40f8b3b27a675326509fbf4ace68a6822ecbd0b539cf29e476ad9aa3a3ef
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      EDGE_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/msedge/config
        target: /config
