name: documenso

services:
  documenso:
    image: documenso/documenso:v2.19.0@sha256:a0592ef8edbc8d74e5e236d9c2dffb3fc4f0104a3ea1c52baaae4673799d8d91
    container_name: documenso
    restart: unless-stopped
    depends_on:
      documenso-db:
        condition: service_healthy
    ports:
      - "20030:3000"
    environment:
      PORT: "3000"
      NEXTAUTH_SECRET: HlLbSGA2KdCiFkgFK2QCbocNRMQYCuyHcdw0HybLaks
      NEXT_PRIVATE_ENCRYPTION_KEY: z7k14oDge1HeVUG2LlT3aQeypUTr8NH-JID_K6tYUO0
      NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY: utotV_gd2gwCIO5BGo-E72vSqI24hOittOVkWfbqBAg
      NEXT_PUBLIC_WEBAPP_URL: http://localhost:20030
      NEXT_PRIVATE_INTERNAL_WEBAPP_URL: http://localhost:3000
      NEXT_PRIVATE_DATABASE_URL: postgresql://documenso:GDnYQQ_jrPV7XOwPlYbmd3L9mWi0s_6E@documenso-db:5432/documenso
      NEXT_PRIVATE_DIRECT_DATABASE_URL: postgresql://documenso:GDnYQQ_jrPV7XOwPlYbmd3L9mWi0s_6E@documenso-db:5432/documenso
      NEXT_PUBLIC_UPLOAD_TRANSPORT: database
      NEXT_PRIVATE_SMTP_TRANSPORT: smtp-auth
      NEXT_PRIVATE_SMTP_HOST: smtp.example.com
      NEXT_PRIVATE_SMTP_PORT: "587"
      NEXT_PRIVATE_SMTP_USERNAME: documenso-4RI74RoG
      NEXT_PRIVATE_SMTP_PASSWORD: _QDGh5oFrd3NgFD21CHkgqG1
      NEXT_PRIVATE_SMTP_FROM_NAME: Documenso
      NEXT_PRIVATE_SMTP_FROM_ADDRESS: noreply@localhost
  documenso-db:
    image: postgres:15.19@sha256:724292da1f2e50bdccfc3302ce75bbba7f4a6076701b588cc795fcac65683550
    container_name: documenso-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: documenso
      POSTGRES_PASSWORD: GDnYQQ_jrPV7XOwPlYbmd3L9mWi0s_6E
      POSTGRES_DB: documenso
    volumes:
      - documenso_database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U documenso -d documenso"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  documenso_database:
    name: documenso_database
    driver: local
