name: linuxserver-azahar
services:
  app:
    image: linuxserver/azahar:12126.1.2@sha256:31508bb1f84718378b2a48789f3bea015fc758043d4a557bdd517b0bee1a596f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/azahar/config
        target: /config
