name: linuxserver-azahar
services:
  app:
    image: linuxserver/azahar:12126.1.2@sha256:496cc371eca09b92a08c8d1b5e816326dea3d1c6d8d3ed303651deeafe720260
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/azahar/config
        target: /config
