name: big-bear-ollama-cpu
services:
  big-bear-ollama-cpu:
    container_name: big-bear-ollama-cpu
    image: ollama/ollama:0.11.8
    restart: unless-stopped
    environment:
      - PORT=11434
    volumes:
      - /DATA/AppData/$AppID/.ollama:/root/.ollama
    ports:
      - '11434:11434'
    devices:
      - /dev/kfd
      - /dev/dri
