name: big-bear-nightscout
services:
  big-bear-nightscout:
    container_name: big-bear-nightscout
    image: nightscout/cgm-remote-monitor:15.0.3
    restart: unless-stopped
    ports:
      - '1337:1337'
    environment:
      NODE_ENV: production
      TZ: Etc/UTC
      INSECURE_USE_HTTP: 'true'
      MONGO_CONNECTION: mongodb://big-bear-nightscout-mongo:27017/nightscout
      API_SECRET: 48f875fa-0e03-416f-b9d6-19c9afc4e194
      ENABLE: careportal rawbg iob
      AUTH_DEFAULT_ROLES: denied
    depends_on:
      - big-bear-nightscout-mongo
    networks:
      - big-bear-nightscout-network
  big-bear-nightscout-mongo:
    container_name: big-bear-nightscout-mongo
    image: mongo:4.4
    networks:
      - big-bear-nightscout-network
    volumes:
      - /DATA/AppData/$AppID/mongo-data:/data/db:cached
networks:
  big-bear-nightscout-network:
    driver: bridge
