name: big-bear-stirling-pdf
services:
  big-bear-stirling-pdf:
    container_name: big-bear-stirling-pdf
    image: stirlingtools/stirling-pdf:1.2.0
    restart: unless-stopped
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - SECURITY_ENABLE_LOGIN=true
      - SECURITY_INITIALLOGIN_USERNAME=bigbear
      - SECURITY_INITIALLOGIN_PASSWORD=4500733e-a0f8-4605-a712-fd267404956a
      - CSRF_DISABLED=false
      - DEFAULT_LOCALE=en-US
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_US
    volumes:
      - /DATA/AppData/$AppID/tessdata:/usr/share/tessdata
      - /DATA/AppData/$AppID/configs:/configs
    ports:
      - '8080:8080'
