name: big-bear-mailpit
services:
  app:
    image: axllent/mailpit:v1.27
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/data:/data
    environment:
      - TZ=UTC
    ports:
      - '8025:8025'
      - '1025:1025'
