name: big-bear-rocket-chat
services:
  app:
    container_name: big-bear-rocket-chat
    image: rocket.chat:6.13.1
    restart: unless-stopped
    environment:
      MONGO_OPLOG_URL: mongodb://db:27017/local
      ROOT_URL: http://localhost:3000
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rocketchat-net
  db:
    image: mongo:4.4.28
    container_name: big-bear-rocketchat-db
    volumes:
      - /DATA/AppData/$AppID/db:/data/db
    healthcheck:
      test:
        - CMD
        - mongo
        - '--eval'
        - db.stats()
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - rocketchat-net
networks:
  rocketchat-net:
    driver: bridge
