name: big-bear-n8n
services:
  app:
    container_name: n8n
    image: n8nio/n8n:1.110.0
    restart: unless-stopped
    ports:
      - '5678:5678'
    links:
      - db-n8n
    volumes:
      - /DATA/AppData/$AppID/.n8n:/home/node/.n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=db-n8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=bigbearcasaos
      - DB_POSTGRESDB_PASSWORD=bigbearcasaos
    depends_on:
      db-n8n:
        condition: service_healthy
  db-n8n:
    container_name: db-n8n
    image: postgres:14.2
    restart: on-failure
    volumes:
      - /DATA/AppData/$AppID/pgdata:/var/lib/postgresql/data
      - >-
        /DATA/AppData/$AppID/db/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    environment:
      - POSTGRES_PASSWORD=bigbearcasaos
      - POSTGRES_USER=bigbearcasaos
      - POSTGRES_DB=n8n
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -h localhost -U bigbearcasaos -d n8n
      interval: 5s
      timeout: 5s
      retries: 10
