name: linuxserver-pycharm
services:
  app:
    image: linuxserver/pycharm:2026.2.1@sha256:73fa7d2649be7fa0d50ff135b9670bf9e9a017a69f697b5d5a9cc621ad2b51e2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pycharm/config
        target: /config
