name: big-bear-minio
services:
  app:
    image: minio/minio:RELEASE.2024-02-24T17-11-14Z
    container_name: big-bear-minio
    volumes:
      - /DATA/AppData/$AppID:/data
    ports:
      - '9010:9000'
      - '9011:9001'
    environment:
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ROOT_USER: minioadmin
    restart: unless-stopped
    command:
      - server
      - '--console-address'
      - ':9001'
      - /data
