name: big-bear-jfa-go
services:
  big-bear-jfa-go:
    container_name: big-bear-jfa-go
    image: hrfee/jfa-go:latest
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/.config/jfa-go:/data
      - /DATA/AppData/$AppID/jellyfin:/jf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8056:8056'
