# Configuration for dozzle setup

# Name of the big-bear-dozzle application
name: big-bear-dozzle
# Service definitions for the big-bear-dozzle application
services:
  # Service name: app
  # The `app` service definition
  app:
    # Name of the container
    container_name: big-bear-dozzle
    # Image to be used for the container
    image: amir20/dozzle:v10.7.4@sha256:068025ea622a1ce3e343a138dd9a962429b5187a133aca301bb4991fe7d2b708
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting docker.sock to allow docker management via the container
      - /var/run/docker.sock:/var/run/docker.sock
    # Ports mapping between host and container
    ports:
      # Mapping port 8888 of the host to port 8080 of the container
      - "8888:8080"
