name: big-bear-btop
services:
  big-bear-btop:
    container_name: big-bear-btop
    image: bigbeartechworld/big-bear-btop:0.1.4
    restart: unless-stopped
    privileged: true
    environment:
      - GOTTY_AUTH_USER=bigbear
      - GOTTY_AUTH_PASS=password
      - GOTTY_AUTH_ENABLED=true
    volumes:
      - /proc:/proc
      - /sys:/sys
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/$AppID/config:/root/.config/btop
    ports:
      - '7681:7681'
