name: big-bear-homebridge
services:
  big-bear-homebridge:
    container_name: big-bear-homebridge
    image: homebridge/homebridge:2024-05-02
    restart: unless-stopped
    environment:
      - TZ=UTC
    privileged: true
    network_mode: host
    volumes:
      - /DATA/AppData/$AppID/data:/homebridge
