# Configuration for homebridge setup

# Name of the big-bear-homebridge application
name: big-bear-homebridge
# Service definitions for the big-bear-homebridge application
services:
  # Service name: big-bear-homebridge
  # The `big-bear-homebridge` service definition
  big-bear-homebridge:
    # Name of the container
    container_name: big-bear-homebridge
    # Image to be used for the container
    image: homebridge/homebridge:2024-05-02@sha256:ecdcb11b69a3c73e5c8e638a5f06ecd16d5212d8bdb52b58f1759f1fdcac6c9e
    # Container restart policy
    restart: unless-stopped
    # Environment Variables
    environment:
      - TZ=UTC # Timezone
    privileged: true
    network_mode: host
    # Volumes HOST:CONTAINER
    volumes:
      - homebridge_data:/homebridge
volumes:
  homebridge_data:
    name: homebridge_data
    driver: local
