name: big-bear-plex
services:
  big-bear-plex:
    container_name: big-bear-plex
    image: linuxserver/plex:1.42.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=
    restart: unless-stopped
    network_mode: host
    volumes:
      - /DATA/AppData/$AppID/config:/config
      - /DATA/AppData/$AppID/tv:/tv
      - /DATA/AppData/$AppID/movies:/movies
