name: linuxserver-diskover
services:
  app:
    image: linuxserver/diskover:5.0.13@sha256:2551a96eba8eb82fa684e0e21a1f3548c205d1057579cedae49cdfaf48c907b0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      ES_HOST: ''
      ES_PORT: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/diskover/config
        target: /config
      - type: bind
        source: /DATA/AppData/diskover/data
        target: /data
