name: big-bear-ayon
services:
  big-bear-ayon:
    container_name: big-bear-ayon
    image: ynput/ayon:1.3.6-20240823
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:5000/api/info
      interval: 10s
      timeout: 2s
      retries: '3'
    volumes:
      - /DATA/AppData/$AppID/addons:/addons
      - /DATA/AppData/$AppID/storage:/storage
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '5000:5000'
    expose:
      - '5000'
    networks:
      - big-bear-ayon-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=ayon
      - POSTGRES_PASSWORD=ayon
      - POSTGRES_DB=ayon
    volumes:
      - /DATA/AppData/$AppID/postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ayon
      interval: 10s
      timeout: 5s
      retries: '5'
    expose:
      - '5432'
    networks:
      - big-bear-ayon-network
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/redis:/data
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping | grep PONG
      interval: 5s
      timeout: 5s
      retries: '5'
    expose:
      - '6379'
    networks:
      - big-bear-ayon-network
networks:
  big-bear-ayon-network:
    driver: bridge
