name: spot-dl
services:
  app:
    image: spotdl/spotify-downloader:v4.5.2
    restart: unless-stopped
    ports:
      - target: 8800
        published: 8800
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/Media/Music
        target: /music
      - type: bind
        source: /DATA/AppData/coolstore-spotdl/config
        target: /config
    command:
      - web
      - '--host'
      - 0.0.0.0
      - '--port'
      - '8800'
      - '--web-use-output-dir'
    tty: true
