name: big-bear-dashdot
services:
  app:
    image: mauricenino/dashdot:6.2.0
    ports:
      - "3001:3001"
    volumes:
      - dashdot_data:/mnt/host
    privileged: true
volumes:
  dashdot_data:
    name: dashdot_data
    driver: local
