name: linuxserver-vivaldi
services:
  app:
    image: linuxserver/vivaldi:8.2.4133@sha256:6a0dfbac6b44dcf78cdb0c075286f8b93eeccb810a579c63150daa264096383d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      VIVALDI_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vivaldi/config
        target: /config
