name: big-bear-peppermint
services:
  app:
    container_name: big-bear-peppermint
    image: pepperlabs/peppermint:latest
    restart: always
    privileged: false
    networks:
      - default
    ports:
      - 3000:3000/tcp
      - 5003:5003/tcp
    environment:
      - API_URL=http://local.host:5003
      - DB_HOST=db
      - DB_PASSWORD=casaos
      - DB_USERNAME=casaos
      - SECRET=peppermint4life
    depends_on:
      db:
        condition: service_started
        required: true
  db:
    container_name: db
    image: postgres:15.5
    restart: always
    environment:
      - PGID=1000
      - POSTGRES_DB=casaos
      - POSTGRES_PASSWORD=casaos
      - POSTGRES_USER=casaos
      - PUID=1000
      - TZ=Etc/UTC
    ports:
      - 5432:5432/tcp
    volumes:
      - /DATA/AppData/$AppID/postgres/data:/var/lib/postgresql/data
    networks:
      - default
    privileged: false
networks:
  default:
    name: peppermint_default
