# Configuration for big-bear-domainlocker setup
name: big-bear-domainlocker
# Service definitions for the big-bear-domainlocker application
services:
  # Main Domain Locker service configuration
  domain-locker:
    container_name: domain-locker # Name of the running container
    image: ghcr.io/lissy93/domain-locker@v0.2.4@sha256:7a3ade47e8187193f92ea1ea5b913d699cc09635 # Image to be used
    ports: # Mapping ports from the host OS to the container
      - 8180:8080
    volumes: # Mounting directories for persistent data storage
      - domainlocker_data:/data
    restart: unless-stopped # Policy to restart unless stopped
    # Networks to be attached to the container
    networks:
      - big_bear_domainlocker_network
  # Networks to be attached to the container
networks:
  # Defines network configurations for the services
  big_bear_domainlocker_network:
    driver: bridge # Uses bridge network driver
volumes:
  domainlocker_data:
    name: domainlocker_data
    driver: local