name: readerr
services:
  app:
    image: hotio/readarr
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8787
        published: 8787
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /portainer/downloads
        target: /downloads
      - type: bind
        source: /portainer/books
        target: /books
