name: big-bear-crafty
services:
  big-bear-crafty:
    container_name: big-bear-crafty
    image: registry.gitlab.com/crafty-controller/crafty-4:4.5.3
    restart: unless-stopped
    environment:
      - TZ=UTC
    ports:
      - '8443:8443'
      - '8123:8123'
      - 19132:19132/udp
      - 25500-25600:25500-25600
    volumes:
      - /DATA/AppData/$AppID/data/backups:/crafty/backups
      - /DATA/AppData/$AppID/data/logs:/crafty/logs
      - /DATA/AppData/$AppID/data/servers:/crafty/servers
      - /DATA/AppData/$AppID/data/config:/crafty/app/config
      - /DATA/AppData/$AppID/data/import:/crafty/import
