name: skysend

services:
  skysend:
    image: skyfay/skysend:v2.12.2@sha256:64fcc07d2dfedb15efa72badc538c452c9e889125bdd9f1e35347f14de108cc0
    container_name: skysend
    restart: unless-stopped
    ports:
      - "23001:3000"
    volumes:
      - skysend_data:/data
      - skysend_uploads:/uploads
    environment:
      BASE_URL: http://localhost:23001
      DATA_DIR: /data
      UPLOADS_DIR: /uploads

volumes:
  skysend_data:
    name: skysend_data
    driver: local
  skysend_uploads:
    name: skysend_uploads
    driver: local
