name: big-bear-portainer-agent
services:
  app:
    container_name: portainer-agent
    image: portainer/agent:2.33.1
    network_mode: bridge
    ports:
      - '9001:9001'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
