name: linuxserver-duplicati
services:
  app:
    image: linuxserver/duplicati:2.4.0@sha256:48897c65f01c7cb34a90d6aa722fd5674f3d5b9f3d82fa2f279141836826c1e3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SETTINGS_ENCRYPTION_KEY: ''
      CLI_ARGS: ''
      DUPLICATI__WEBSERVICE_PASSWORD: ''
    ports:
      - target: 8200
        published: 8200
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/duplicati/config
        target: /config
      - type: bind
        source: /DATA/AppData/duplicati/backups
        target: /backups
      - type: bind
        source: /DATA/AppData/duplicati/source
        target: /source
