name: big-bear-scrypted
services:
  scrypted:
    container_name: scrypted
    image: koush/scrypted:v0.123.58-jammy-full
    network_mode: host
    environment:
      - >-
        SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer
        SET_THIS_TO_SOME_RANDOM_TEXT
      - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update
    volumes:
      - /DATA/AppData/$AppID/data:/server/volume
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    labels:
      - com.centurylinklabs.watchtower.scope=scrypted
  watchtower:
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=SET_THIS_TO_SOME_RANDOM_TEXT
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_SCOPE=scrypted
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - com.centurylinklabs.watchtower.scope=scrypted
    ports:
      - '10444:8080'
    command: '--interval 3600 --cleanup --scope scrypted'
