name: linuxserver-yaak
services:
  app:
    image: linuxserver/yaak:2026.8.1@sha256:976586095765719653ba972301f9604cc97e94c6ef377324d032603ed91acf09
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/yaak/config
        target: /config
