name: big-bear-pihole-unbound
services:
  app:
    container_name: big-bear-pihole-unbound
    image: bigbeartechworld/big-bear-pihole-unbound:2025.08.0
    restart: unless-stopped
    environment:
      TZ: America/Chicago
      FTLCONF_webserver_api_password: your_password
      FTLCONF_dns_upstreams: 127.0.0.1#5353
    volumes:
      - /DATA/AppData/$AppID/etc:/etc/pihole/
      - /DATA/AppData/$AppID/dnsmasq.d:/etc/dnsmasq.d/
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8080:80/tcp
      - 10443:443/tcp
    networks:
      - pihole-unbound-network
networks:
  pihole-unbound-network:
    driver: bridge
