name: big-bear-speedtest-tracker
services:
  big-bear-speedtest-tracker:
    container_name: big-bear-speedtest-tracker
    ports:
      - '8080:80'
      - '8443:443'
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=mysql
      - DB_HOST=big-bear-speedtest-tracker-db
      - DB_PORT=3306
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=casaos
      - DB_PASSWORD=casaos
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/$AppID/config:/config
      - /DATA/AppData/$AppID/web:/etc/ssl/web
    image: linuxserver/speedtest-tracker:1.6.6
    restart: unless-stopped
    depends_on:
      - big-bear-speedtest-tracker-db
    networks:
      - big_bear_speedtest_tracker_network
  big-bear-speedtest-tracker-db:
    image: mariadb:10
    container_name: big-bear-speedtest-tracker-db
    restart: always
    environment:
      - MARIADB_DATABASE=speedtest_tracker
      - MARIADB_USER=casaos
      - MARIADB_PASSWORD=casaos
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    volumes:
      - /DATA/AppData/$AppID/mysql:/var/lib/mysql
    networks:
      - big_bear_speedtest_tracker_network
networks:
  big_bear_speedtest_tracker_network:
    driver: bridge
