name: big-bear-flcontainers-guacamole
services:
  app:
    image: flcontainers/guacamole:1.6.0
    container_name: big-bear-flcontainers-guacamole
    restart: always
    environment:
      tz: UTC
      EXTENSIONS: auth-totp,auth-ldap
    ports:
      - '8080:8080'
