name: big-bear-ghost
services:
  app:
    container_name: big-bear-ghost
    image: ghost:6.0.6-alpine
    restart: on-failure
    networks:
      - ghost-network
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: casaos
      database__connection__database: ghost
      url: http://localhost:2368
    volumes:
      - /DATA/AppData/$AppID/content:/var/lib/ghost/content
    ports:
      - '2368:2368'
    depends_on:
      - db
  db:
    container_name: big-bear-ghost-db
    image: mysql:8.0
    restart: on-failure
    volumes:
      - /DATA/AppData/$AppID/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: ghost
      MYSQL_DATABASE: ghost
      MYSQL_PASSWORD: casaos
      MYSQL_ROOT_PASSWORD: casaos
    networks:
      - ghost-network
networks:
  ghost-network:
    driver: bridge
