name: big-bear-monica
services:
  big-bear-monica:
    container_name: big-bear-monica
    image: monica:4.1.2
    restart: unless-stopped
    environment:
      - APP_KEY=80356f7073c4f7834187b25a9d32cd2a
      - DB_HOST=big-bear-monica-db
      - DB_USERNAME=usermonica
      - DB_PASSWORD=passwordmonica
    volumes:
      - /DATA/AppData/$AppID/storage:/var/www/html/storage
    ports:
      - '8080:80'
    networks:
      - big_bear_monica_network
  big-bear-monica-db:
    image: mariadb:10.6.11
    container_name: big-bear-monica-db
    environment:
      - TZ=UTC
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_DATABASE=monica
      - MARIADB_USER=usermonica
      - MARIADB_PASSWORD=passwordmonica
    volumes:
      - /DATA/AppData/$AppID/mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      - big_bear_monica_network
networks:
  big_bear_monica_network:
    driver: bridge
