name: big-bear-cloudflared-web
services:
  big-bear-cloudflared-web:
    container_name: big-bear-cloudflared-web
    image: wisdomsky/cloudflared-web:2025.8.1
    restart: unless-stopped
    network_mode: host
    environment:
      - WEBUI_PORT=14333
      - EDGE_IP_VERSION=auto
      - PROTOCOL=auto
      - METRICS_ENABLE=false
      - METRICS_PORT=60123
      - BASIC_AUTH_USER=admin
      - BASIC_AUTH_PASS=""
