name: big-bear-firefox # Name of the CasaOS application
services:
  firefox:
    container_name: big-bear-firefox # Name of the Docker container
    image: linuxserver/firefox:1.2404.1 # Docker image for the Firefox browser
    ports:
      - "3000:3000" # Expose port 3000 for HTTP VNC access
      - "3001:3001" # Expose port 3001 for HTTPS VNC access
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - FIREFOX_CLI=https://community.bigbeartechworld.com/ # Set the default URL to Big Bear Tech World
    shm_size: 1gb # Allocate 1 GB of shared memory
    volumes:
      - firefox_config:/config # Mount the config directory for persistent data
volumes:
  firefox_config:
    name: firefox_config
    driver: local
