name: big-bear-ollama-nvidia
services:
  big-bear-ollama-nvidia:
    container_name: big-bear-ollama-nvidia
    image: ollama/ollama:0.11.8
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/.ollama:/root/.ollama
    ports:
      - '11434:11434'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
