name: big-bear-immich
services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:v1.140.1
    ports:
      - '2283:2283'
    volumes:
      - /DATA/AppData/$AppID/upload:/usr/src/app/upload
    environment:
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: casaos
      DB_PASSWORD: casaos
      DB_DATABASE_NAME: immich
      DB_PORT: '5432'
      REDIS_HOSTNAME: immich-redis
      IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      - big_bear_immich_network
  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.140.1
    volumes:
      - /DATA/AppData/$AppID/model-cache:/cache
    environment:
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: casaos
      DB_PASSWORD: casaos
      DB_DATABASE_NAME: casaos
      DB_PORT: 5432
      REDIS_HOSTNAME: immich-redis
    restart: unless-stopped
    networks:
      - big_bear_immich_network
  redis:
    container_name: immich-redis
    image: >-
      redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
    networks:
      - big_bear_immich_network
  database:
    container_name: immich-postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: casaos
      POSTGRES_USER: casaos
      POSTGRES_DB: immich
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /DATA/AppData/$AppID/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - big_bear_immich_network
networks:
  big_bear_immich_network:
    driver: bridge
