name: big-bear-home-assistant
services:
  app:
    container_name: big-bear-home-assistant
    image: ghcr.io/home-assistant/home-assistant:2025.9.1
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    network_mode: host
