name: big-bear-pd3f
services:
  web:
    container_name: big-bear-pd3f
    image: pd3f/pd3f:latest
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/uploads:/uploads/
    ports:
      - '1616:5000'
    command:
      - gunicorn
      - app:app
      - '--bind=0.0.0.0:5000'
    depends_on:
      - redis
      - parsr
      - worker
      - ocr_worker
    networks:
      - big-bear-pd3f-network
  parsr:
    image: axarev/parsr:v1.2.2
    networks:
      - big-bear-pd3f-network
    expose:
      - 3001
  redis:
    image: redis:6-alpine
    networks:
      - big-bear-pd3f-network
    expose:
      - 6379
  worker:
    image: pd3f/pd3f:latest
    depends_on:
      - parsr
      - redis
    networks:
      - big-bear-pd3f-network
    volumes:
      - /DATA/AppData/$AppID/cache:/root/.cache/
      - /DATA/AppData/$AppID/to-ocr:/to-ocr/
      - /DATA/AppData/$AppID/uploads:/uploads/
    environment:
      - KEEP_RESULTS_HOURS=24
    command:
      - rq
      - worker
      - '-u'
      - redis://redis:6379
      - '--results-ttl'
      - '86400'
  ocr_worker:
    image: pd3f/pd3f-ocr:latest
    networks:
      - big-bear-pd3f-network
    volumes:
      - /DATA/AppData/$AppID/to-ocr:/to-ocr/
networks:
  big-bear-pd3f-network:
    name: big-bear-pd3f-network
