name: big-bear-tailscale
services:
  big-bear-tailscale:
    container_name: big-bear-tailscale
    image: tailscale/tailscale:v1.86.5
    restart: unless-stopped
    environment:
      - TS_SERVE_CONFIG=""
      - TS_ACCEPT_DNS=false
      - TS_AUTH_ONCE=false
      - TS_AUTHKEY=""
      - TS_HOSTNAME=""
      - TS_ROUTES=""
      - TS_EXTRA_ARGS=""
      - TS_USERSPACE=true
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /DATA/AppData/$AppID/state:/var/lib/tailscale
      - /DATA/AppData/$AppID/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
