name: big-bear-nextcloud
services:
  nextcloud:
    container_name: nextcloud
    image: bigbeartechworld/big-bear-nextcloud-with-smbclient:0.0.10
    restart: unless-stopped
    ports:
      - '7580:80'
    volumes:
      - /DATA/AppData/$AppID/html:/var/www/html
    environment:
      - POSTGRES_HOST=db-nextcloud
      - REDIS_HOST=redis-nextcloud
      - POSTGRES_PASSWORD=casaos
      - POSTGRES_USER=casaos
      - POSTGRES_DB=nextcloud
      - NEXTCLOUD_ADMIN_USER=casaos
      - NEXTCLOUD_ADMIN_PASSWORD=casaos
      - TRUSTED_PROXIES=
      - OVERWRITEPROTOCOL=http
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=1024M
    depends_on:
      db-nextcloud:
        condition: service_healthy
      redis-nextcloud:
        condition: service_healthy
    networks:
      - nextcloud_network
  db-nextcloud:
    container_name: db-nextcloud
    image: postgres:14.2
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=casaos
      - POSTGRES_USER=casaos
      - POSTGRES_DB=nextcloud
    networks:
      - nextcloud_network
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U casaos -d nextcloud
      interval: 10s
      timeout: 5s
      retries: 5
  redis-nextcloud:
    container_name: redis-nextcloud
    user: '1000:1000'
    image: redis:6.2.6
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/redis:/data
    networks:
      - nextcloud_network
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
  cron:
    image: bigbeartechworld/big-bear-nextcloud-with-smbclient:0.0.10
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      db-nextcloud:
        condition: service_healthy
      redis-nextcloud:
        condition: service_healthy
    networks:
      - nextcloud_network
networks:
  nextcloud_network:
    driver: bridge
