name: linuxserver-mysql-workbench
services:
  app:
    image: linuxserver/mysql-workbench:8.0.47@sha256:e3e266f611846fb31a6741a9c46f6cd0b6e54e2fc3b3b77021aab75fe93762f6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mysql-workbench/config
        target: /config
