# Configuration for matterbridge setup

# Application Name
name: big-bear-matterbridge
# Services used in the application
services:
  # The `big-bear-matterbridge` service for the Matterbridge application
  big-bear-matterbridge:
    # Name of the container
    container_name: big-bear-matterbridge
    # Docker image to be used
    image: luligu/matterbridge:3.10.9@sha256:c01108d904ecb908fcf0c7a42debf3fc071dbede4997b5bdef9cee5631a2427a
    # Restart policy for the service
    restart: unless-stopped
    # Network mode set to host for Matter mdns support
    network_mode: host
    # Volume mappings for persistent storage
    volumes:
      - matterbridge_Matterbridge:/root/Matterbridge
      - matterbridge_.matterbridge:/root/.matterbridge
volumes:
  matterbridge_.matterbridge:
    name: matterbridge_.matterbridge
    driver: local
  matterbridge_Matterbridge:
    name: matterbridge_Matterbridge
    driver: local
