# Configuration for matterbridge setup

# Application Name
name: big-bear-matterbridge
# Services used in the application
services:
  # The `big-bear-matterbridge` service for the Matterbridge application
  big-bear-matterbridge:
    # Name of the container
    container_name: big-bear-matterbridge
    # Docker image to be used
    image: luligu/matterbridge:3.10.6@sha256:97e16340825c9b31f17d34f8dc47aa12251b39045705585feeed6f2d04b720ac
    # Restart policy for the service
    restart: unless-stopped
    # Network mode set to host for Matter mdns support
    network_mode: host
    # Volume mappings for persistent storage
    volumes:
      - matterbridge_Matterbridge:/root/Matterbridge
      - matterbridge_.matterbridge:/root/.matterbridge
volumes:
  matterbridge_.matterbridge:
    name: matterbridge_.matterbridge
    driver: local
  matterbridge_Matterbridge:
    name: matterbridge_Matterbridge
    driver: local
