# Configuration for matterbridge setup

# Application Name
name: big-bear-matterbridge
# Services used in the application
services:
  # The `big-bear-matterbridge` service for the Matterbridge application
  big-bear-matterbridge:
    # Name of the container
    container_name: big-bear-matterbridge
    # Docker image to be used
    image: luligu/matterbridge:3.10.8@sha256:1ec50ecd0694adfdd781a13c5df8ab6f9712925f0b5ecea9662c308b6bc35062
    # Restart policy for the service
    restart: unless-stopped
    # Network mode set to host for Matter mdns support
    network_mode: host
    # Volume mappings for persistent storage
    volumes:
      - matterbridge_Matterbridge:/root/Matterbridge
      - matterbridge_.matterbridge:/root/.matterbridge
volumes:
  matterbridge_.matterbridge:
    name: matterbridge_.matterbridge
    driver: local
  matterbridge_Matterbridge:
    name: matterbridge_Matterbridge
    driver: local
