name: big-bear-convertx
services:
  big-bear-convertx:
    container_name: big-bear-convertx
    image: ghcr.io/c4illin/convertx:v0.14.1
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - JWT_SECRET=c8330437-e6ae-4cf0-9837-4d1326457e32
      - HTTP_ALLOWED=true
    volumes:
      - /DATA/AppData/$AppID/data:/app/data
