name: casaos-toolbox
services:
  app:
    image: wisdomsky/casaos-toolbox:0.2
    restart: unless-stopped
    network_mode: host
    environment:
      FORCE_HTTPS: false
      WEBUI_PORT: 8088
      DB_HOST: 0.0.0.0
      DB_PORT: 33066
      DB_DATABASE: casaos
      DB_USERNAME: casaos
      DB_PASSWORD: casaos
    volumes:
      - /usr/bin/casaos-cli:/usr/bin/casaos-cli
      - /etc/casaos/gateway.ini:/casaos/gateway.ini
      - /var/lib/casaos/apps:/casaos/apps
      - /var/lib/casaos/www:/casaos/www
  db:
    image: mariadb:13.0.2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: casaos
      MYSQL_DATABASE: casaos
      MYSQL_USER: casaos
      MYSQL_PASSWORD: casaos
    ports:
      - target: 3306
        published: '33066'
        protocol: tcp
    volumes:
      - /DATA/AppData/casaos-toolbox/mysql:/var/lib/mysql
