name: big-bear-ghostfolio
services:
  big-bear-ghostfolio:
    container_name: big-bear-ghostfolio
    image: ghostfolio/ghostfolio:2.195.0
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: '3333'
      ACCESS_TOKEN_SALT: 5a7f9e0d-0e64-4c19-8279-bbe8b4c590f4
      DATABASE_URL: >-
        postgresql://ghostfolio:casaospassword@big-bear-ghostfolio-db:5432/ghostfolio?sslmode=prefer
      JWT_SECRET_KEY: 534e820d-da30-4dd3-baf9-0511847c478a
      POSTGRES_DB: ghostfolio
      POSTGRES_USER: ghostfolio
      POSTGRES_PASSWORD: casaospassword
      REDIS_HOST: big-bear-ghostfolio-redis
      REDIS_PASSWORD: casaosredispassword
      REDIS_PORT: '6379'
    ports:
      - '3333:3333'
    depends_on:
      big-bear-ghostfolio-db:
        condition: service_healthy
      big-bear-ghostfolio-redis:
        condition: service_healthy
    networks:
      - big_bear_ghostfolio_network
  big-bear-ghostfolio-db:
    container_name: big-bear-ghostfolio-db
    image: postgres:15.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ghostfolio
      POSTGRES_USER: ghostfolio
      POSTGRES_PASSWORD: casaospassword
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d ghostfolio -U ghostfolio
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /DATA/AppData/$AppID/data/db:/var/lib/postgresql/data
    networks:
      - big_bear_ghostfolio_network
  big-bear-ghostfolio-redis:
    container_name: big-bear-ghostfolio-redis
    image: redis:7-alpine
    restart: unless-stopped
    command: |
      --requirepass casaosredispassword
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - /DATA/AppData/$AppID/data/redis:/data
    networks:
      - big_bear_ghostfolio_network
networks:
  big_bear_ghostfolio_network:
    driver: bridge
