name: linuxserver-snipe-it
services:
  app:
    image: linuxserver/snipe-it:8.0.4@sha256:60bb523aeca290d65fe8bcef33654020eaa7f82fb4a14df52e75a31e3b2d3764
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      APP_KEY: $APP_KEY
      APP_URL: $APP_URL
      MYSQL_PORT_3306_TCP_ADDR: $MYSQL_PORT_3306_TCP_ADDR
      MYSQL_PORT_3306_TCP_PORT: $MYSQL_PORT_3306_TCP_PORT
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      APP_DEBUG: $APP_DEBUG
      APP_ENV: $APP_ENV
      APP_FORCE_TLS: $APP_FORCE_TLS
      APP_LOCALE: $APP_LOCALE
      MAIL_PORT_587_TCP_ADDR: $MAIL_PORT_587_TCP_ADDR
      MAIL_PORT_587_TCP_PORT: $MAIL_PORT_587_TCP_PORT
      MAIL_ENV_FROM_ADDR: $MAIL_ENV_FROM_ADDR
      MAIL_ENV_FROM_NAME: $MAIL_ENV_FROM_NAME
      MAIL_ENV_ENCRYPTION: $MAIL_ENV_ENCRYPTION
      MAIL_ENV_USERNAME: $MAIL_ENV_USERNAME
      MAIL_ENV_PASSWORD: $MAIL_ENV_PASSWORD
    ports:
      - target: 8080
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/snipe-it/config
        target: /config
