# Configuration for kavita setup

# Name of the big-bear-kavita application
name: big-bear-kavita
# Service definitions for the big-bear-kavita application
services:
  # Service name: big-bear-kavita
  # The `big-bear-kavita` service definition
  big-bear-kavita:
    # Name of the container
    container_name: big-bear-kavita
    # Image to be used for the container
    image: jvmilazz0/kavita:0.8.8
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      - kavita_data_kavita-config:/kavita/config
      - kavita_media_data_books:/books
      - kavita_media_data_comics:/comics
      - kavita_media_data_manga:/manga
    # Ports mapping between host and container
    ports:
      # Mapping port 5000 of the host to port 5000 of the container
      - "5000:5000"
volumes:
  kavita_data_kavita-config:
    name: kavita_data_kavita-config
    driver: local
  kavita_media_data_books:
    name: kavita_media_data_books
    driver: local
  kavita_media_data_comics:
    name: kavita_media_data_comics
    driver: local
  kavita_media_data_manga:
    name: kavita_media_data_manga
    driver: local
