name: big-bear-adguard-home-host
services:
  big-bear-adguard-home-host:
    container_name: big-bear-adguard-home-host
    image: adguard/adguardhome:v0.107.65
    volumes:
      - /DATA/AppData/$AppID/data/work:/opt/adguardhome/work
      - /DATA/AppData/$AppID/data/conf:/opt/adguardhome/conf
    restart: unless-stopped
    network_mode: host
