name: big-bear-minio
services:
  app:
    image: bigbeartechworld/big-bear-minio:RELEASE.2025-10-15T17-29-55Z
    container_name: big-bear-minio
    volumes:
      - minio_data:/data
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ROOT_USER: minioadmin
    restart: unless-stopped
    command:
      - server
      - "--console-address"
      - ":9001"
      - /data
volumes:
  minio_data:
    name: minio_data
    driver: local
