name: big-bear-erugo
services:
  big-bear-erugo:
    container_name: big-bear-erugo
    image: wardy784/erugo:0.1.1
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/storage:/var/www/html/storage
    ports:
      - '9997:80'
