name: big-bear-kopia
services:
  big-bear-kopia:
    container_name: big-bear-kopia
    image: ghcr.io/thespad/kopia-server:v0.17.0-spad3
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=UTC
      - KOPIA_HTTPS=true
      - KOPIA_UI_USERNAME=casaos
      - KOPIA_UI_PASSWORD=casaos
      - KOPIA_PASSWORD=casaos
      - REFRESH_INTERVAL=
    volumes:
      - /DATA/AppData/$AppID/config:/config
      - /DATA/AppData/$AppID/home:/backups/home:ro
      - /var/lib/docker/volumes:/backups/docker:ro
      - /DATA/AppData/$AppID/repository:/repository
      - /tmp:/tmp:shared
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '51515:51515'
    cap_add:
      - SYS_ADMIN
