name: big-bear-plex-nvidia
services:
  big-bear-plex-nvidia:
    container_name: big-bear-plex-nvidia
    image: linuxserver/plex:1.42.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=
      - CPU_FALLBACK=true
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
    network_mode: host
    volumes:
      - /DATA/AppData/$AppID/config:/config
      - /DATA/AppData/$AppID/tv:/tv
      - /DATA/AppData/$AppID/movies:/movies
    devices:
      - /dev/dri:/dev/dri
      - /dev/dvb:/dev/dvb
    deploy:
      resources:
        reservations:
          memory: 256M
          devices:
            - capabilities:
                - gpu
