name: big-bear-semaphore
services:
  big-bear-semaphore:
    container_name: big-bear-semaphore
    image: semaphoreui/semaphore:v2.16.19
    restart: unless-stopped
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: big-bear-semaphore-db
      SEMAPHORE_DB_PORT: '3306'
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: semaphore
      SEMAPHORE_ADMIN_PASSWORD: password
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@example.com
      SEMAPHORE_ADMIN: admin
      TZ: UTC
    volumes:
      - /DATA/AppData/$AppID/home:/etc/semaphore
      - /DATA/AppData/$AppID/lib:/var/lib/semaphore
    ports:
      - '3000:3000'
    networks:
      - big-bear-semaphore-network
  big-bear-semaphore-db:
    container_name: big-bear-semaphore-db
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: semaphore
    networks:
      - big-bear-semaphore-network
networks:
  big-bear-semaphore-network:
    driver: bridge
