name: linuxserver-signal
services:
  app:
    image: linuxserver/signal:8.27.0@sha256:22bf16fa9647cd1282f11341bdb22518e3d8ac0f6927a98311c7fdbef71d1646
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/signal/config
        target: /config
