name: metube-youtubedl
services:
  app:
    image: alexta69/metube:2025-07-30
    restart: unless-stopped
    environment:
      UID: $PUID
      GID: $PGID
      DARK_MODE: true
    ports:
      - target: 8081
        published: 48111
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
