name: big-bear-nocodb
services:
  big-bear-nocodb:
    image: nocodb/nocodb:0.264.6
    container_name: big-bear-nocodb
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://nocodb:nocodb@big-bear-nocodb-db:5432/nocodb
      - NC_AUTH_JWT_SECRET=899499fc-36a0-4131-b077-7bb9f051ac9b
      - NC_REDIS_URL=redis://default:casaos@big-bear-nocodb-redis:6379
    ports:
      - '8080:8080'
    volumes:
      - /DATA/AppData/$AppID/data:/usr/src/app/data
    networks:
      - big-bear-nocodb-network
  big-bear-nocodb-db:
    container_name: big-bear-nocodb-db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: nocodb
      POSTGRES_USER: nocodb
      POSTGRES_PASSWORD: nocodb
    volumes:
      - /DATA/AppData/$AppID/pgdata:/var/lib/postgresql/data
    networks:
      - big-bear-nocodb-network
  big-bear-nocodb-redis:
    image: redis:alpine
    container_name: big-bear-nocodb-redis
    restart: unless-stopped
    command:
      - redis-server
      - '--requirepass'
      - casaos
    volumes:
      - /DATA/AppData/$AppID/redis:/data
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - big-bear-nocodb-network
networks:
  big-bear-nocodb-network:
    driver: bridge
