name: big-bear-portracker
services:
  big-bear-portracker:
    container_name: big-bear-portracker
    image: mostafawahied/portracker:1.1
    restart: unless-stopped
    environment:
      - PORT=4999
      - DATABASE_PATH=/data/portracker.db
      - TRUSTED_LOCAL_EMAIL=your@email.com
      - CACHE_TIMEOUT_MS=30000
      - DISABLE_CACHE=false
      - INCLUDE_UDP=false
      - DEBUG=false
    volumes:
      - /DATA/AppData/$AppID/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '4999:4999'
