name: Sync App Versions

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - main
    paths:
      - 'apps/*/docker-compose.yml'

jobs:
  check-and-fix-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.3.0
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check for version mismatches
        id: check-versions
        run: |
          # Run the version check script
          if bun .github/scripts/check-version-mismatches.js; then
            echo "has_mismatches=false" >> $GITHUB_OUTPUT
            echo "✅ No version mismatches found"
          else
            echo "has_mismatches=true" >> $GITHUB_OUTPUT
            echo "⚠️ Version mismatches detected"
          fi

      - name: Fix version mismatches
        if: steps.check-versions.outputs.has_mismatches == 'true'
        run: |
          echo "🔧 Fixing version mismatches..."
          bun .github/scripts/fix-version-mismatches.js

      - name: Create Pull Request
        if: steps.check-versions.outputs.has_mismatches == 'true'
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: sync app.json versions with docker-compose.yml'
          title: 'chore: sync app.json versions with docker-compose.yml'
          body: |
            ## 🔄 Automatic Version Sync
            
            This PR automatically updates `app.json` versions to match the versions in `docker-compose.yml` files.
            
            ### Changes
            This PR was automatically created by the version sync workflow to keep app metadata in sync with Docker image versions.
            
            ### How it works
            - The workflow runs daily and on every push to main that changes docker-compose.yml files
            - It detects mismatches between app.json and docker-compose.yml versions
            - Automatically updates app.json files to match
            - Creates this PR with the automerge label
            
            ---
            🤖 This is an automated PR. It will auto-merge if all checks pass.
          branch: automated/sync-versions
          delete-branch: true
          labels: |
            automerge
            automated
            dependencies
          assignees: ${{ github.repository_owner }}

      - name: Enable auto-merge
        if: steps.create-pr.outputs.pull-request-number
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ steps.create-pr.outputs.pull-request-number }} --auto --squash

      - name: Summary
        if: steps.check-versions.outputs.has_mismatches == 'true'
        run: |
          if [ -n "${{ steps.create-pr.outputs.pull-request-number }}" ]; then
            echo "✅ Created PR #${{ steps.create-pr.outputs.pull-request-number }} to fix version mismatches"
            echo "🔗 ${{ steps.create-pr.outputs.pull-request-url }}"
          fi
