name: big-bear-nextcloud-smb
services:
  big-bear-nextcloud-smb:
    container_name: big-bear-nextcloud-smb
    image: bigbeartechworld/big-bear-nextcloud-with-smbclient:0.0.10
    restart: unless-stopped
    ports:
      - '7580:80'
    volumes:
      - /DATA/AppData/$AppID/html:/var/www/html
    environment:
      - POSTGRES_HOST=big-bear-nextcloud-smb-db
      - REDIS_HOST=big-bear-nextcloud-smb-redis
      - POSTGRES_PASSWORD=casaos
      - POSTGRES_USER=casaos
      - POSTGRES_DB=nextcloud
      - NEXTCLOUD_ADMIN_USER=casaos
      - NEXTCLOUD_ADMIN_PASSWORD=casaos
      - TRUSTED_PROXIES=
      - OVERWRITEPROTOCOL=http
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=1024M
    depends_on:
      big-bear-nextcloud-smb-db:
        condition: service_healthy
      big-bear-nextcloud-smb-redis:
        condition: service_healthy
    networks:
      - big_bear_nextcloud_network
  big-bear-nextcloud-smb-db:
    container_name: big-bear-nextcloud-smb-db
    image: postgres:14.2
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=casaos
      - POSTGRES_USER=casaos
      - POSTGRES_DB=nextcloud
    networks:
      - big_bear_nextcloud_network
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U casaos -d nextcloud
      interval: 10s
      timeout: 5s
      retries: 5
  big-bear-nextcloud-smb-redis:
    container_name: big-bear-nextcloud-smb-redis
    user: '1000:1000'
    image: redis:6.2.6
    restart: on-failure
    volumes:
      - /DATA/AppData/$AppID/redis:/data
    networks:
      - big_bear_nextcloud_network
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
  big-bear-nextcloud-smb-cron:
    container_name: big-bear-nextcloud-smb-cron
    image: bigbeartechworld/big-bear-nextcloud-with-smbclient:0.0.10
    restart: on-failure
    volumes:
      - /DATA/AppData/$AppID/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      big-bear-nextcloud-smb-db:
        condition: service_healthy
      big-bear-nextcloud-smb-redis:
        condition: service_healthy
    networks:
      - big_bear_nextcloud_network
networks:
  big_bear_nextcloud_network:
    driver: bridge
